name: Python CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cicd-learning .

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build package
        run: |
          mkdir -p dist
          tar -czf dist/cicd-learning.tar.gz app.py test_app.py requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd-learning-package
          path: dist/cicd-learning.tar.gz

      - name: Run tests
        run: python -m unittest test_app.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cicd-learning-package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag cicd-learning:latest namrathatg/cicd-learning:latest

      - name: Push Docker image
        run: docker push namrathatg/cicd-learning:latest

      - name: Deploy package
        run: |
          mkdir -p deployment
          echo "Deploying application..."
          ls -la